.TH shsub 1

.SH NAME

shsub - compile the shell template to a shell script
and execute it

.SH SYNOPSIS

\fBshsub\fR [\fIoptions\fR] [\fIfile\fR\]

.PP
\fBshsub\fR reads the shell template from \fIfile\fR.
If \fIfile\fR is omitted, \fBshsub\fR reads from stdin.

.SH DESCRIPTION

.PP
A shell template is text
with shell commands and expressions embedded in.

.PP
The shell commands are surrounded by \fB<%\fR and \fB%>\fR.
Each \fB<%\fIcmd\fB%>\fR is compiled to \fIcmd\fR.

.PP
The shell expressions are surrounded by \fB<%=\fR and \fB%>\fR.
Each \fB<%=\fIexpr\fB%>\fR is compiled to
\fBprintf %s \[dq]\fIexpr\fB\[dq]\fR.
Leading and trailing spaces, tabs, and newlines of \fIexpr\fR
are removed.
Double quotes in \fIexpr\fR are automatically escaped.

.PP
Ordinary text is compiled to the command printing that text.

.PP
\fB<%%\fR and \fB%%>\fR are escaping tokens representing
literal \fB<%\fR and \fB%>\fR.

.PP
If \fB-%>\fR is used instead of \fB%>\fR,
\fBshsub\fR ignores the following newline.

.PP
If the first line of the shell template begins with
\fB#!\fR (\fIshebang\fR), it will be ignored.
This is for the convenience of making executable shell templates.

.SH READING INPUT

When the template is stdin,
no argument will be passed to the template
and \fB$0\fR could be any value.
If the template contains commands reading stdin,
e.g. \fBread\fR(1), the behavior is unspecific.

When the template is a named file,
all arguments after the file name are passed to the template,
and \fB$progname\fR is set to the template name.
The template can safely read stdin.
However, \fB$0\fR could still be any value.

.SH OPTIONS

.TP
\fB\-s\fR \fIshell\fR
Set which shell is used to execute the compiled script.
By default,
\fBshsub\fR uses \fB/bin/sh\fR.
Setting \fB-s cat\fR is a convenient way to examine the compiled script.

.TP
.B \-h
Print the brief usage.

.TP
.B \-v
Print the version information.
