.TH shsub 1

.SH NAME

shsub - substitute embedded shell commands and expressions with their
outputs and results

.SH SYNOPSIS

\fBshsub\fR [\fIoptions\fR] [\fIfile\fR\]

.PP
\fBshsub\fR reads the shell template from \fIfile\fR,
and prints the result to stdout.
If \fIfile\fR is omitted, \fBshsub\fR reads from stdin.

.SH DESCRIPTION

.PP
A shell template is text
with shell commands and expressions embedded in.

.PP
The shell commands are surrounded by \fB<%\fR and \fB%>\fR.

.PP
Each \fB<%\fIcmd\fB%>\fR is substituted
with the output of the command.

.PP
Ordinary text is converted to the command printing that text,
then the command is substituted by its output.
Thus control structure can be used in shell commands.

.PP
The shell expressions are surrounded by \fB<%=\fR and \fB%>\fR.

.PP
Each \fB<%=\fIexpr\fB%>\fR is substituted with
the output of the command \fBprintf %s \[dq]\fIexpr\fB\[dq]\fR.
Leading and trailing spaces, tabs, and newlines of \fIexpr\fR are removed.
Double quotes in \fIexpr\fR are automatically escaped.

.PP
\fB<%%\fR and \fB%%>\fR are escape tokens representing
literal \fB<%\fR and \fB%>\fR.

.PP
If \fB-%>\fR is used instead of \fB%>\fR,
\fBshsub\fR trims the following newline.

.SH CAVEATS

When \fBshsub\fR reads from stdin,
and the shell template contains commands reading from stdin,
e.g. \fBread\fR(1), the behavior is unspecific.

.SH OPTIONS

.TP
\fB\-s\fR \fIshell\fR
Set which shell is used.
By default,
\fBshsub\fR uses \fB/bin/sh\fR.

.TP
.B \-h
Print the brief usage.

.TP
.B \-v
Print the version information.
